<a href="https://colab.research.google.com/github/An4PDM/Disciplina-IA-2026-02/blob/main/Exercicios_Python_Ana_Paula_6A.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Imprima "Hello, World!" no console.

In [ ]:
print("Hello, World!")

Hello, World!


2. Crie um programa que peça ao usuário dois números e exiba a soma deles.

In [ ]:

a = int(input("Insira um número: "))
b = int(input("Insira outro número: "))

soma = a + b
print(f"A soma entre {a} e {b} é igual a {soma}")



Insira um número: 5
Insira outro número: 3
A soma entre 5 e 3 é igual a 8


3. Solicite o raio de um círculo e calcule sua área. Use a fórmula área = π * r².


In [ ]:

from math import pi

r = float(input("Insira o valor do raio: "))
area = pi * (r**2)

print(f"A área do círculo é igual a {area:.2f}") # Formatação para retornar com só duas casas decimais

Insira o valor do raio: 5
A área do círculo é igual a 78.54


4. Converta uma temperatura fornecida em Celsius para Fahrenheit usando a fórmula F = C * 9/5 + 32.

In [ ]:
c = float(input("Insira o valor (em Celsius) da temperatura: "))
f = c * 9/5 + 32

print(f"Conversão para Fahrenheit: {f}")

Insira o valor (em Celsius) da temperatura: 30
Conversão para Fahrenheit: 86.0


5. Crie um programa que imprima a tabuada de um número fornecido pelo usuário.

In [ ]:
n = int(input("Insira um número de 1 a 10: "))
x = 1

while x <= 10: # Enquanto x for menor ou igual a 10, o loop continuará.
    y = n*x
    print(f"{n} x {x} = {y}")
    x += 1


Insira um número de 1 a 10: 8
8 x 1 = 8
8 x 2 = 16
8 x 3 = 24
8 x 4 = 32
8 x 5 = 40
8 x 6 = 48
8 x 7 = 56
8 x 8 = 64
8 x 9 = 72
8 x 10 = 80


6. Faça um programa que exiba todos os números pares de 1 a 20.

In [ ]:
x = 1
while x <= 20:
  if (x % 2 == 0): # Verifica se o "resto" da divisão por 2 é igual a 0
    print(x)
  x += 1



2
4
6
8
10
12
14
16
18
20


7. Solicite um número ao usuário e informe se ele é par ou ímpar.

In [ ]:
n = int(input("Informe um valor: "))

if(n % 2 == 0):
  print(f"O número {n} é par.")
else:
  print(f"O número {n} é ímpar.")

Informe um valor: 3
O número 3 é ímpar.


8. Crie um programa que verifique se uma palavra é um palíndromo (ex: "radar").


In [ ]:
palavra = input("Digite uma palavra: ")

if palavra == palavra[::-1]: # Não definimos inicio e fim, e o -1 indica que queremos "ler" a palavra de trás para frente
  print(f"A palavra {palavra} é um palindromo!")

else:
  print("Não é palíndromo.")

Digite uma palavra: bolo
Não é palíndromo.


9. Fatorial de um Número:
 Calcule o fatorial de um número fornecido pelo usuário.


In [ ]:

from math import factorial

n = int(input("insira um valor inteiro: "))
print(factorial(n))


insira um valor inteiro: 5
120


10. Sequência de Fibonacci: Imprima os primeiros 10 números da sequência de Fibonacci.


In [ ]:
lista = [0,1]

while len(lista) < 10:
  prox_elemento = lista[-1] + lista[-2]
  lista.append(prox_elemento)

print(lista)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]


11. Lista de Números: Crie uma lista de números e exiba o maior e o menor número.


In [ ]:
lista = [12,45,2,30,80,8,56]
maior = max(lista)
menor = min(lista)

print(f"O maior número da lista é {maior}.")
print(f"O menor número da lista é {menor}.")

O maior número da lista é 80.
O menor número da lista é 2.


12. Contagem de Caracteres: Conte o número de ocorrências de cada caractere em uma string
fornecida

In [ ]:
palavra = input("Digite uma palavra: ")

palavra = list(palavra) # Transforma a palavra em uma lista
contador = {} # A chave será a letra e o valor será o numero de ocorrencias

for letra in palavra: # Itera cada item (letra)
  if letra in contador:
    # Adiciona +1 caso já exista
    contador[letra] +=1

  else:
    contador[letra] = 1

print(contador)


Digite uma palavra: abobora
{'a': 2, 'b': 2, 'o': 2, 'r': 1}


13. Ordenação de Lista: Dada uma lista de números, ordene-a em ordem crescente.

In [ ]:
lista = [12,5,34,50,1,0,17,21]

lista.sort()
lista

[0, 1, 5, 12, 17, 21, 34, 50]

14. Soma dos Elementos de uma Lista: Calcule a soma de todos os elementos em uma lista.


In [ ]:
lista = [10,15,5,4]

print(sum(lista))

34


15. Média de uma Lista: Calcule a média dos números em uma lista.

In [ ]:
lista = [10,15,5]

soma = sum(lista)
tamanho = len(lista)

print(soma/tamanho)

10.0


16. Manipulação de Strings: Crie um programa que inverta uma string fornecida pelo usuário.

In [10]:
palavra = input("Insira uma palavra: ")
palavra = list(palavra)
palavra = palavra[::-1] # Inverte toda a lista

# Retorna a lista como uma única string concatenada novamente com o método .join()
palavra = "".join(palavra) # O separador ficou indefinido

print(palavra)


Insira uma palavra: anapaula
aluapana


17. Dicionário de Contagem de Palavras: Conte a frequência de cada palavra em uma string fornecida pelo
usuário.

18. Número Primo: Crie um programa que verifique se um número fornecido é primo.

Como Descobrir se um Número é Primo:

Para saber se um número grande é primo, você testa a divisão dele pelos números primos menores (2, 3, 5, 7, etc.):
- Veja se ele é par (se for e for maior que 2, não é primo).
- Some os algarismos para ver se divide por 3.
- Veja se termina em 0 ou 5 para saber se divide por 5.
- Se a divisão exata não acontecer por nenhum primo menor cuja raiz quadrada seja menor ou igual ao número testado, ele é primo

In [29]:
from math import sqrt

primos_menores = [2,3,5,7,11]

n = int(input("Insira um valor para descobrir se é primo: "))
raiz = sqrt(n) # Guarda a raíz desse número


for x in primos_menores:
  # Verifica se o valor fornecido é divisível por algum dos primos menores que a raiz desse valor fornecido.
  if x <= raiz:
    if n % x == 0:
      print("Não é um número primo.")
      break # Paramos o loop pois já não seria necessário verificar mais vezes

else:
  print("É um número primo.")


Insira um valor para descobrir se é primo: 1
É um número primo.


19. Jogo de Adivinhação: Implemente um jogo onde o usuário deve adivinhar um número gerado aleatoriamente pelo computador.

In [42]:
import numpy as np

n_gerado = np.random.randint(1,10) # Geração de valor inteiro aleatório
tentativas = 1
print("Você terá 5 tentativas ao total.")
n_usuario = int(input("Descubra qual número foi gerado de 1 a 10: "))

while tentativas < 5: # O usuario terá, no maximo, 5 tentativas

  if n_gerado == n_usuario:
    print("Parabéns! Você acertou. ")
    break # Se acertar, o loop é parado.

  else:
    n_usuario = int(input("Tente novamente: "))

  tentativas += 1

print(f"O número aleatório gerado foi {n_gerado}.")

Você terá 5 tentativas ao total.
Descubra qual número foi gerado de 1 a 10: 4
Tente novamente: 3
Tente novamente: 7
Parabéns! Você acertou. 
O número aleatório gerado foi 7.


20. Matriz Transposta: Dada uma matriz (lista de listas), crie sua matriz transposta.

  - Matriz transposta: As linhas viram colunas, as colunas viram linhas.

In [49]:
import numpy as np

matriz = np.array([[4,16,12],[9,10,31],[34,2,45]]) # Criação manual da matriz
matriz_transposta = np.transpose(matriz) # Método transpose do numpy
print(matriz)
print("--------------")
print(matriz_transposta)

[[ 4 16 12]
 [ 9 10 31]
 [34  2 45]]
--------------
[[ 4  9 34]
 [16 10  2]
 [12 31 45]]


21. Busca Binária: Implemente a busca binária para encontrar um elemento em uma
lista ordenada.

Busca Binária: A lista deve estar em ordem crescente, o programa lê o número do meio e descarta a metade caso seja menor que o numero procurado.


In [3]:
lista = [20,15,23,45,71,10,5]

n = int(input("Qual número será procurado? ")) # Elemento procurado

# Primeiro, ordenamos a lista
lista.sort()
print(lista)

i = lista[0:] # Inicio da lista
f = lista[:0] # Fim da lista

while i <= f:
# Verificação do índice do valor do meio
    posicao = len(lista) // 2 # Operador de divisão que "ignora" a casa decimal

    if lista[posicao] == n:
      print(f"O número procurado {n} foi encontrado.")
      break

    elif lista[posicao] < n:
      lista = lista[posicao:] # Eliminamos a metade da esquerda (numeros menores)
      continue

    elif lista[posicao] > n:
      lista = lista[:posicao] # Eliminamos a metade da direita (numeros maiores)
      continue
  else:
    print(f"O número {n} não está presente na lista.")





Qual número será procurado? 1
[5, 10, 15, 20, 23, 45, 71]


IndexError: list index out of range

22. Criptografia de Cifra de César: Crie uma função para criptografar uma mensagem usando a cifra de
César.

23. Descriptografar Cifra de César: Crie uma função para descriptografar uma mensagem cifrada com a
cifra de César.

24. Validação de CPF: Implemente uma função para validar um CPF brasileiro.

25. Classificação de Números: Classifique uma lista de números em três categorias: positivos,
negativos e zeros.

26. Calculadora Simples: Crie uma calculadora que possa realizar adição, subtração,
multiplicação e divisão.

27. Anagramas: Verifique se duas palavras são anagramas (ou seja, se são formadas
pelas mesmas letras).

28. Gráfico de Barras: Use a biblioteca matplotlib para criar um gráfico de barras com dados fornecidos pelo usuário.

29. Números FizzBuzz: Implemente o clássico problema FizzBuzz para números de 1 a 100.
- Número múltiplo de 3: Fizz;
- Número múltiplo de 5: Buzz;
- Número múltiplo de 3 e 5: FizzBuzz

In [43]:
n = 1

while (n <= 100):

  if  n % 3 == 0 and n % 5 == 0:
    print("FizzBuzz!")

  elif n % 5 == 0:
    print("Buzz!")

  elif n % 3 == 0:
    print("Fizz!")

  else:
    print(n)

  n += 1


1
2
Fizz!
4
Buzz!
Fizz!
7
8
Fizz!
Buzz!
11
Fizz!
13
14
FizzBuzz!
16
17
Fizz!
19
Buzz!
Fizz!
22
23
Fizz!
Buzz!
26
Fizz!
28
29
FizzBuzz!
31
32
Fizz!
34
Buzz!
Fizz!
37
38
Fizz!
Buzz!
41
Fizz!
43
44
FizzBuzz!
46
47
Fizz!
49
Buzz!
Fizz!
52
53
Fizz!
Buzz!
56
Fizz!
58
59
FizzBuzz!
61
62
Fizz!
64
Buzz!
Fizz!
67
68
Fizz!
Buzz!
71
Fizz!
73
74
FizzBuzz!
76
77
Fizz!
79
Buzz!
Fizz!
82
83
Fizz!
Buzz!
86
Fizz!
88
89
FizzBuzz!
91
92
Fizz!
94
Buzz!
Fizz!
97
98
Fizz!
Buzz!


30. Jogo da Forca: Desenvolva um jogo simples da forca onde o usuário deve adivinhar uma palavra.